#!/usr/bin/env python3
"""
FFT Twiddle Factor Generator for COE Files
Generates twiddle factor pairs (cos, sin) for Xilinx IP cores
Each 32-bit word contains: [cos(15:0), sin(15:0)]
"""

import math
import argparse
import sys

def generate_twiddle_factors(N_points, output_file="twiddle_factors.coe"):
    """
    Generate twiddle factors for N-point FFT and save to COE file
    
    Args:
        N_points: Number of FFT points (must be power of 2)
        output_file: Output COE filename
    """
    
    # Validate input
    if N_points <= 0 or (N_points & (N_points - 1)) != 0:
        raise ValueError(f"N_points must be a positive power of 2, got {N_points}")
    
    # Number of twiddle factors needed
    num_twiddles = N_points // 2
    
    print(f"Generating {num_twiddles} twiddle factor pairs for {N_points}-point FFT")
    print(f"Output file: {output_file}")
    
    # Generate twiddle factors
    twiddle_data = []
    
    for k in range(num_twiddles):
        # Calculate angle: -2*pi*k/N (negative for FFT)
        angle = -2.0 * math.pi * k / N_points
        
        # Calculate cos and sin values
        cos_val = math.cos(angle)
        sin_val = math.sin(angle)
        
        # Convert to Q15 fixed-point (16-bit signed, 15 fractional bits)
        # Range: -1.0 to +0.999969482421875 maps to -32768 to +32767
        cos_fixed = int(round(cos_val * 32767))
        sin_fixed = int(round(sin_val * 32767))
        
        # Ensure values are in valid 16-bit signed range
        cos_fixed = max(-32768, min(32767, cos_fixed))
        sin_fixed = max(-32768, min(32767, sin_fixed))
        
        # Convert to unsigned 16-bit for bit manipulation
        cos_unsigned = cos_fixed & 0xFFFF
        sin_unsigned = sin_fixed & 0xFFFF
        
        # Combine into 32-bit word: [cos(31:16), sin(15:0)]
        combined = (cos_unsigned << 16) | sin_unsigned
        
        twiddle_data.append({
            'index': k,
            'angle_deg': math.degrees(angle),
            'cos_float': cos_val,
            'sin_float': sin_val,
            'cos_fixed': cos_fixed,
            'sin_fixed': sin_fixed,
            'combined': combined
        })
        
        # Print first few and key values for verification
        if k < 5 or k == num_twiddles // 4 or k == num_twiddles // 2 or k == 3 * num_twiddles // 4 or k == num_twiddles - 1:
            print(f"k={k:3d}: angle={angle:8.4f} rad ({math.degrees(angle):7.2f}°), "
                  f"cos={cos_val:8.5f} → {cos_fixed:6d}, sin={sin_val:8.5f} → {sin_fixed:6d}, "
                  f"word=0x{combined:08X}")
    
    # Write COE file
    with open(output_file, 'w') as f:
        # COE file header
        f.write(f"; FFT Twiddle Factors for {N_points}-point FFT\n")
        f.write(f"; Generated by twiddle_generator.py\n")
        f.write(f"; Format: Each 32-bit word = [cos(31:16), sin(15:0)]\n")
        f.write(f"; Values in Q15 fixed-point format (1 sign + 15 fractional bits)\n")
        f.write(f"; Total entries: {num_twiddles}\n")
        f.write(";\n")
        f.write("memory_initialization_radix=16;\n")
        f.write("memory_initialization_vector=\n")
        
        # Write twiddle factor data
        for i, twiddle in enumerate(twiddle_data):
            # Write 32-bit hex value
            if i == len(twiddle_data) - 1:
                # Last entry ends with semicolon
                f.write(f"{twiddle['combined']:08X};\n")
            else:
                # Other entries end with comma
                f.write(f"{twiddle['combined']:08X},\n")
    
    print(f"\nCOE file written successfully!")
    print(f"Memory depth: {num_twiddles} words")
    print(f"Memory width: 32 bits")
    print(f"File size: {len(twiddle_data)} entries")
    
    # Generate verification data
    print(f"\nVerification samples:")
    verify_indices = [0, 1, num_twiddles//8, num_twiddles//4, num_twiddles//2, num_twiddles-1]
    for idx in verify_indices:
        if idx < num_twiddles:
            t = twiddle_data[idx]
            print(f"  Index {idx:3d}: 0x{t['combined']:08X} = cos({t['cos_fixed']:6d}) + j*sin({t['sin_fixed']:6d})")

def generate_testbench_data(N_points, output_file="twiddle_tb.txt"):
    """Generate testbench verification data"""
    num_twiddles = N_points // 2
    
    with open(output_file, 'w') as f:
        f.write(f"// Testbench data for {N_points}-point FFT twiddle factors\n")
        f.write(f"// Format: index, hex_value, cos_decimal, sin_decimal\n")
        
        for k in range(num_twiddles):
            angle = -2.0 * math.pi * k / N_points
            cos_val = math.cos(angle)
            sin_val = math.sin(angle)
            cos_fixed = max(-32768, min(32767, int(round(cos_val * 32767))))
            sin_fixed = max(-32768, min(32767, int(round(sin_val * 32767))))
            cos_unsigned = cos_fixed & 0xFFFF
            sin_unsigned = sin_fixed & 0xFFFF
            combined = (cos_unsigned << 16) | sin_unsigned
            
            f.write(f"{k:4d}, 0x{combined:08X}, {cos_fixed:6d}, {sin_fixed:6d}\n")
    
    print(f"Testbench data written to {output_file}")

def main():
    parser = argparse.ArgumentParser(description='Generate FFT twiddle factors in COE format')
    parser.add_argument('N_points', type=int, help='Number of FFT points (must be power of 2)')
    parser.add_argument('-o', '--output', default='twiddle_factors.coe', help='Output COE filename')
    parser.add_argument('-t', '--testbench', action='store_true', help='Also generate testbench data file')
    
    args = parser.parse_args()
    
    try:
        # Generate COE file
        generate_twiddle_factors(args.N_points, args.output)
        
        # Generate testbench data if requested
        if args.testbench:
            tb_file = args.output.replace('.coe', '_tb.txt')
            generate_testbench_data(args.N_points, tb_file)
            
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()